DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sgdb_app') THEN
        CREATE ROLE sgdb_app LOGIN PASSWORD 'troque_esta_senha_em_producao';
    END IF;
END
$$;

GRANT USAGE ON SCHEMA public TO sgdb_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO sgdb_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sgdb_app;

GRANT EXECUTE ON FUNCTION fn_calcular_prazo_sla(TIMESTAMPTZ, INTEGER, INTEGER) TO sgdb_app;
GRANT EXECUTE ON FUNCTION sp_abrir_chamado(INTEGER, INTEGER, INTEGER, INTEGER, VARCHAR, TEXT, INTEGER, INTEGER) TO sgdb_app;
GRANT EXECUTE ON FUNCTION sp_atribuir_tecnico(INTEGER, INTEGER, INTEGER) TO sgdb_app;
GRANT EXECUTE ON FUNCTION sp_registrar_resolucao(INTEGER, TEXT, INTEGER, INTEGER) TO sgdb_app;
GRANT EXECUTE ON FUNCTION sp_fechar_chamado(INTEGER, INTEGER, INTEGER) TO sgdb_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO sgdb_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO sgdb_app;
